{% set name = "gensim" %}
{% set version = "4.1.2" %}
{% set sha256 = "1932c257de4eccbb64cc40d46e8577a25f5f47b94b96019a969fb36150f11d15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0 
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.29.23
    - numpy >=1.17.0
    - setuptools
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cython >=0.29.23
    - dataclasses   # [py<37]
    - scipy >=0.18.1
    - smart_open >=1.8.1

test:
  requires:
    - pytest
    - testfixtures
    - morfessor
    - cython
    - pyemd
    - mock
    - pip
  imports:
    - gensim
    - gensim.corpora
    - gensim.models
    - gensim.parsing
    - gensim.scripts
    - gensim.similarities
    - gensim.test
    - gensim.topic_coherence
  commands:
    - pip check

about:
  home: https://github.com/RaRe-Technologies/gensim
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: Topic Modelling for Humans
  description: |
    Gensim is a Python library for topic modelling, document indexing
    and similarity retrieval with large corpora.
    Target audience is the natural language processing (NLP)
    and information retrieval (IR) community.
  doc_url: https://radimrehurek.com/gensim/
  dev_url: https://github.com/RaRe-Technologies/gensim

extra:
  recipe-maintainers:
    - souravsingh
    - mpenkov
