{% set name = "gensim" %}
{% set version = "4.4.0" %}
{% set sha256 = "0c1c8984f18512aba04332b45dc58698ac277dfa1d314a190a3f07edc48c31ac" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RaRe-Technologies/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # gensim and pyemd currently aren't available on s390x
  skip: true  # [py<38 or s390x]
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=3.1.3
    - numpy {{numpy}}
    - setuptools
    - wheel
    - numpy >=1.18.5  # [py>=39]
    - scipy
    - wheelhouse_uploader
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.7.0
    - smart_open >=1.8.1
  run_constrained:
    - Pyro4 >=4.27

test:
  imports:
    - gensim
    - gensim.corpora
    - gensim.models
    - gensim.parsing
    - gensim.scripts
    - gensim.similarities
    - gensim.test
    - gensim.topic_coherence
  requires:
    - pip
    - pytest
    - testfixtures
  source_files:
    - gensim/test
  commands:
    - pip check
    - pytest -v gensim/test -k "not test_distance"

about:
  home: https://github.com/RaRe-Technologies/gensim
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: Topic Modelling for Humans
  description: |
    Gensim is a Python library for topic modelling, document indexing
    and similarity retrieval with large corpora.
    Target audience is the natural language processing (NLP)
    and information retrieval (IR) community.
  doc_url: https://radimrehurek.com/gensim/
  dev_url: https://github.com/RaRe-Technologies/gensim

extra:
  recipe-maintainers:
    - souravsingh
    - mpenkov
