{% set name = "gensim" %}
{% set version = "3.0.1" %}
{% set sha256 = "4827012f6f020ac4f4067c2a2a88542391917113faaa417505e1ee8a1e7e2650" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # https://github.com/RaRe-Technologies/gensim/pull/1647
    - 0001-Fix-test_filename_filtering-test.patch

build:
  number: 0
  features:
    - vc{{ vc }}   # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
    - numpy 1.11.*
  build:
    - {{ compiler('c') }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.18.1
    - six >=1.5.0
    - smart_open >=1.2.1
    
test:
  requires:
    - nose
    - testfixtures
    - morfessor
    - scikit-learn ==0.18.2
    - pyemd
  imports:
    - gensim
    - gensim.corpora
    - gensim.models
    - gensim.models.wrappers
    - gensim.parsing
    - gensim.scripts
    - gensim.similarities
    - gensim.sklearn_api
    - gensim.summarization
    - gensim.test
    - gensim.topic_coherence
  commands:
    - nosetests --exe -v gensim
    
about:
  home: http://github.com/RaRe-Technologies/gensim
  license: LGPL-3.0
  license_file: COPYING
  license_family: LGPL
  summary: 'Topic Modelling for Humans'
  description: |
    Gensim is a Python library for topic modelling, document indexing 
    and similarity retrieval with large corpora. 
    Target audience is the natural language processing (NLP) 
    and information retrieval (IR) community.
  doc_url: http://radimrehurek.com/gensim/
  dev_url: https://github.com/RaRe-Technologies/gensim

extra:
  recipe-maintainers:
    - souravsingh
    - tmylk
    - menshikh-iv
