{% set name = "gensim" %}
{% set version = "3.0.0" %}
{% set sha256 = "076c677bcb5335ce286cdb4a16eb98fe2a0dac3c005502c8984f70e1488ac48f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win32 or osx or py34]
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and (py35 or py36)]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.11.3
    - scipy >=0.18.1
    - six >=1.5.0
    - smart_open >=1.2.1
  run:
    - python
    - numpy >=1.11.3
    - scipy >=0.18.1
    - six >=1.5.0
    - smart_open >=1.2.1
    
test:
  requires:
    - nose
    - testfixtures
    - morfessor
    - scikit-learn ==0.18.2
    - pyemd
  imports:
    - gensim
    - gensim.corpora
    - gensim.models
    - gensim.models.wrappers
    - gensim.parsing
    - gensim.scripts
    - gensim.similarities
    - gensim.sklearn_integration
    - gensim.summarization
    - gensim.test
    - gensim.topic_coherence
  commands:
    - nosetests --exe -v gensim
    
about:
  home: http://github.com/RaRe-Technologies/gensim
  license: LGPL-3.0
  license_file: COPYING
  license_family: LGPL
  summary: 'Topic Modelling for Humans'
  description: |
    Gensim is a Python library for topic modelling, document indexing 
    and similarity retrieval with large corpora. 
    Target audience is the natural language processing (NLP) 
    and information retrieval (IR) community.
  doc_url: http://radimrehurek.com/gensim/
  dev_url: https://github.com/RaRe-Technologies/gensim

extra:
  recipe-maintainers:
    - souravsingh
    - tmylk
    - menshikh-iv
