{% set name = "gensim" %}
{% set version = "4.3.0" %}
{% set sha256 = "64bd7ec62990215878822e8b2569d1835054f56cdf53600ddfe9927e31f3b48d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0 
  # gensim and pyemd currently aren't available on s390x
  skip: true  # [py<38 or s390x]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    # NUMPY_STR = 'numpy >= 1.18.5', which is okay as per our current cbc.
    - numpy
    - setuptools
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.7.0
    - smart_open >=1.8.1
    # fuzzytm is actually not used. See: https://github.com/RaRe-Technologies/gensim/issues/3423
    #- fuzzytm 

test:
  imports:
    - gensim
    - gensim.corpora
    - gensim.models
    - gensim.parsing
    - gensim.scripts
    - gensim.similarities
    - gensim.test
    - gensim.topic_coherence
  requires:
    - pip
  commands:
    # pip check fails because of fuzzytm
    - pip check || true  # [not win]
    - pip check || cmd /K "exit /b 0"  # [win]


about:
  home: https://github.com/RaRe-Technologies/gensim
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: Topic Modelling for Humans
  description: |
    Gensim is a Python library for topic modelling, document indexing
    and similarity retrieval with large corpora.
    Target audience is the natural language processing (NLP)
    and information retrieval (IR) community.
  doc_url: https://radimrehurek.com/gensim/
  dev_url: https://github.com/RaRe-Technologies/gensim

extra:
  recipe-maintainers:
    - souravsingh
    - mpenkov
