{% set name = "gensim" %}
{% set version = "4.2.0" %}
{% set sha256 = "995ebd2970a31d47c100aaac10212f47e2bf12e2b06536d38883c951ff34eef1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0 
  # gensim and pyemd currently aren't available on s390x
  skip: true  # [py<36 or s390x]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython ==0.29.28
    - numpy >=1.17.0
    - setuptools
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cython ==0.29.28
    - scipy >=0.18.1
    - smart_open >=1.8.1

test:
  requires:
    - pytest
    - testfixtures
    - cython
    - pyemd  # [not (linux and s390x)]
    - mock
    - pip
    - google-cloud-core >=1.7.1  # [osx and arm64]
  imports:
    - gensim
    - gensim.corpora
    - gensim.models
    - gensim.parsing
    - gensim.scripts
    - gensim.similarities
    - gensim.test
    - gensim.topic_coherence
  commands:
    - pip check

about:
  home: https://github.com/RaRe-Technologies/gensim
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: Topic Modelling for Humans
  description: |
    Gensim is a Python library for topic modelling, document indexing
    and similarity retrieval with large corpora.
    Target audience is the natural language processing (NLP)
    and information retrieval (IR) community.
  doc_url: https://radimrehurek.com/gensim/
  dev_url: https://github.com/RaRe-Technologies/gensim

extra:
  recipe-maintainers:
    - souravsingh
    - mpenkov
