travis:
  secure:
    BINSTAR_TOKEN: ecN7i24QmsWbGKfWOmzAj56rvl5Hh298I3OOFeED99DxJKlpucgxgXMOC2rYDVU8bMRVGZZxLkN1sMyowyM9uaWzrL/N6pA27AvOImMWGMVy7MOYhWHsTK73NAhuIxMMByqtQiOs9gEiOpJaQwxOQSDynae4rSCvul1bTeOyOcbsdk2cT8mkEKfUxy6M50wA20TvW/Q88lEmnC0C1Pa0dysJ85G29jBuH8yh3p4KwtiEyBNfvffqeQuUo1qJWNr9YEXXi/Aq18+DDsR3vLcSHSXMuKUHQ/TE7gq2LAAWEYkEGtOGiQFNeoFujSdmZ5dom6N9uLo/0Ta75VCZoytVgJTADgeghinyBCTBgoXjy3C4e7k/DHaBGdS1ZD42s4MLOYeAU8nJbjTGIlMzdfLzO6KjkLGTk4TBQm7/sDJiSUlf5wq9SrTB3O1UIlwUM5sS5MUC+xg3Btmz/W0HvtzI66oQoFjoh3QQnbGJM1MqpYqcR8QJRofSNfFzW8WDPhEm3bn8AlbjyNY1v9C0zZgHTRuT1Put46u7T0O2W4p6/0U+dsfv+6Iq5VxeKO2ptZRRpBX95Kf3KwEFgHyFsk6BQArU9Ijo3Ud+39wVcD5y9P9iKVugvdoBtL3yl74royeaXZXVwmhKYTYRTBMxe4Ab1Oqdan469Mj5d2JmTnYiKF4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
